name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Deploy on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code (Flake8)
      run: |
        pip install flake8
        flake8 .

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/streamlit-text-gen .

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/streamlit-text-gen

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy the Docker container (if applicable)
      run: echo "Deploy step here (e.g., pull from Docker Hub and deploy to a server)"

